/*
Navicat MySQL Data Transfer

Source Server         : mysql
Source Server Version : 50721
Source Host           : localhost:3306
Source Database       : ssm

Target Server Type    : MYSQL
Target Server Version : 50721
File Encoding         : 65001

Date: 2019-02-02 14:18:14
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for category_
-- ----------------------------
DROP TABLE IF EXISTS `category_`;
CREATE TABLE `category_` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) DEFAULT NULL,
  `createDate` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of category_
-- ----------------------------
INSERT INTO `category_` VALUES ('1', 'category1', '2019-01-15 00:46:45');
INSERT INTO `category_` VALUES ('2', 'category2', '2019-01-15 00:46:45');
INSERT INTO `category_` VALUES ('3', 'category3', '2019-01-30 00:46:56');
INSERT INTO `category_` VALUES ('4', 'category4', '2019-01-22 00:46:51');
INSERT INTO `category_` VALUES ('5', 'category5', '2019-01-19 00:47:17');
INSERT INTO `category_` VALUES ('6', 'producy', '2019-01-04 00:47:07');
INSERT INTO `category_` VALUES ('7', 'producy', '2019-01-25 00:47:03');
INSERT INTO `category_` VALUES ('8', 'producy', '2019-01-09 00:47:12');
INSERT INTO `category_` VALUES ('9', 'item', '2019-01-09 00:47:40');
INSERT INTO `category_` VALUES ('10', 'item', '2019-01-16 12:47:22');
INSERT INTO `category_` VALUES ('11', 'mo324', '2019-02-01 00:47:36');
INSERT INTO `category_` VALUES ('12', 'pooloo', '2019-01-25 11:29:58');
INSERT INTO `category_` VALUES ('13', '234', '2019-01-25 11:30:01');
INSERT INTO `category_` VALUES ('14', '345', '2019-01-25 14:36:35');
INSERT INTO `category_` VALUES ('15', '2342', '2019-01-25 16:07:35');
INSERT INTO `category_` VALUES ('16', '12', '2019-01-25 14:45:39');
INSERT INTO `category_` VALUES ('17', '4354334', '2019-01-25 14:45:46');
INSERT INTO `category_` VALUES ('18', '12', '2019-02-01 21:38:37');

-- ----------------------------
-- Table structure for newscomments_
-- ----------------------------
DROP TABLE IF EXISTS `newscomments_`;
CREATE TABLE `newscomments_` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `newid` int(11) DEFAULT NULL,
  `comments` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=281 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of newscomments_
-- ----------------------------
INSERT INTO `newscomments_` VALUES ('2', '24', '证书状态');
INSERT INTO `newscomments_` VALUES ('3', '24', '3C产品型号');
INSERT INTO `newscomments_` VALUES ('4', '24', '申请人名称');
INSERT INTO `newscomments_` VALUES ('5', '24', '证书编号');
INSERT INTO `newscomments_` VALUES ('6', '24', '分辨率');
INSERT INTO `newscomments_` VALUES ('7', '24', '型号');
INSERT INTO `newscomments_` VALUES ('8', '24', '制造商名称');
INSERT INTO `newscomments_` VALUES ('9', '24', '网络连接方式');
INSERT INTO `newscomments_` VALUES ('10', '24', '产品名称');
INSERT INTO `newscomments_` VALUES ('11', '24', '能效等级');
INSERT INTO `newscomments_` VALUES ('12', '24', '3D类型');
INSERT INTO `newscomments_` VALUES ('13', '24', '操作系统');
INSERT INTO `newscomments_` VALUES ('14', '23', '品牌');
INSERT INTO `newscomments_` VALUES ('15', '23', '冲水按键类型');
INSERT INTO `newscomments_` VALUES ('16', '23', '坐便器类型');
INSERT INTO `newscomments_` VALUES ('17', '23', '盖板是否缓冲');
INSERT INTO `newscomments_` VALUES ('18', '23', '型号');
INSERT INTO `newscomments_` VALUES ('19', '23', '坐便器冲水方式');
INSERT INTO `newscomments_` VALUES ('20', '23', '排水方式');
INSERT INTO `newscomments_` VALUES ('21', '23', '材质');
INSERT INTO `newscomments_` VALUES ('22', '23', '最小坑距');
INSERT INTO `newscomments_` VALUES ('23', '23', '承重');
INSERT INTO `newscomments_` VALUES ('25', '23', '坐便冲水量');
INSERT INTO `newscomments_` VALUES ('26', '23', '同城服务');
INSERT INTO `newscomments_` VALUES ('27', '22', '风格');
INSERT INTO `newscomments_` VALUES ('28', '22', '城市');
INSERT INTO `newscomments_` VALUES ('29', '22', '面料饰面工艺');
INSERT INTO `newscomments_` VALUES ('30', '22', '是否带储物空间');
INSERT INTO `newscomments_` VALUES ('31', '22', '包装体积');
INSERT INTO `newscomments_` VALUES ('32', '22', '颜色分类');
INSERT INTO `newscomments_` VALUES ('33', '22', '附加功能');
INSERT INTO `newscomments_` VALUES ('34', '22', '是否可拆洗');
INSERT INTO `newscomments_` VALUES ('35', '22', '结构工艺');
INSERT INTO `newscomments_` VALUES ('36', '22', '设计元素');
INSERT INTO `newscomments_` VALUES ('37', '22', '几人坐');
INSERT INTO `newscomments_` VALUES ('38', '22', '图案');
INSERT INTO `newscomments_` VALUES ('39', '22', '是否组装');
INSERT INTO `newscomments_` VALUES ('40', '22', '面料');
INSERT INTO `newscomments_` VALUES ('41', '22', '可送货/安装');
INSERT INTO `newscomments_` VALUES ('42', '22', '木质结构工艺');
INSERT INTO `newscomments_` VALUES ('43', '22', '沙发组合形式');
INSERT INTO `newscomments_` VALUES ('44', '22', '产地');
INSERT INTO `newscomments_` VALUES ('45', '22', '是否可定制');
INSERT INTO `newscomments_` VALUES ('46', '22', '品牌');
INSERT INTO `newscomments_` VALUES ('47', '22', '适用对象');
INSERT INTO `newscomments_` VALUES ('48', '22', '材质');
INSERT INTO `newscomments_` VALUES ('49', '22', '款式定位');
INSERT INTO `newscomments_` VALUES ('50', '22', '填充物');
INSERT INTO `newscomments_` VALUES ('51', '22', '填充物硬度');
INSERT INTO `newscomments_` VALUES ('52', '22', '出租车是否可运输');
INSERT INTO `newscomments_` VALUES ('53', '22', '型号');
INSERT INTO `newscomments_` VALUES ('54', '22', '木质材质');
INSERT INTO `newscomments_` VALUES ('55', '22', '是否可预售');
INSERT INTO `newscomments_` VALUES ('56', '22', '安装说明详情');
INSERT INTO `newscomments_` VALUES ('57', '21', '品牌');
INSERT INTO `newscomments_` VALUES ('58', '21', '证书状态');
INSERT INTO `newscomments_` VALUES ('59', '21', '3C产品型号');
INSERT INTO `newscomments_` VALUES ('60', '21', '申请人名称');
INSERT INTO `newscomments_` VALUES ('61', '21', '证书编号');
INSERT INTO `newscomments_` VALUES ('62', '21', '型号');
INSERT INTO `newscomments_` VALUES ('63', '21', '控制方式');
INSERT INTO `newscomments_` VALUES ('64', '21', '制造商名称');
INSERT INTO `newscomments_` VALUES ('65', '21', '款式');
INSERT INTO `newscomments_` VALUES ('66', '21', '产品名称');
INSERT INTO `newscomments_` VALUES ('67', '21', '能效等级');
INSERT INTO `newscomments_` VALUES ('68', '20', '上市时间');
INSERT INTO `newscomments_` VALUES ('69', '20', '款式');
INSERT INTO `newscomments_` VALUES ('70', '20', '是否商场同款');
INSERT INTO `newscomments_` VALUES ('71', '20', '货号');
INSERT INTO `newscomments_` VALUES ('72', '20', '品牌');
INSERT INTO `newscomments_` VALUES ('73', '19', '液晶显示');
INSERT INTO `newscomments_` VALUES ('74', '19', '尘盒容量');
INSERT INTO `newscomments_` VALUES ('75', '19', '外观造型');
INSERT INTO `newscomments_` VALUES ('76', '19', '功能');
INSERT INTO `newscomments_` VALUES ('77', '19', '最高高度');
INSERT INTO `newscomments_` VALUES ('78', '19', '碰撞保护');
INSERT INTO `newscomments_` VALUES ('79', '19', '是否自动充电');
INSERT INTO `newscomments_` VALUES ('80', '19', '电池容量');
INSERT INTO `newscomments_` VALUES ('81', '19', '有无虚拟墙');
INSERT INTO `newscomments_` VALUES ('82', '19', '是否有定时预约功能');
INSERT INTO `newscomments_` VALUES ('83', '19', '货号');
INSERT INTO `newscomments_` VALUES ('84', '19', '颜色分类');
INSERT INTO `newscomments_` VALUES ('85', '19', '清扫路线');
INSERT INTO `newscomments_` VALUES ('86', '19', '是否带遥控器');
INSERT INTO `newscomments_` VALUES ('87', '18', '品牌');
INSERT INTO `newscomments_` VALUES ('88', '18', '转速');
INSERT INTO `newscomments_` VALUES ('89', '18', '证书状态');
INSERT INTO `newscomments_` VALUES ('90', '18', '3C产品型号');
INSERT INTO `newscomments_` VALUES ('91', '18', '申请人名称');
INSERT INTO `newscomments_` VALUES ('92', '18', '额定功率');
INSERT INTO `newscomments_` VALUES ('93', '18', '证书编号');
INSERT INTO `newscomments_` VALUES ('94', '18', '型号');
INSERT INTO `newscomments_` VALUES ('95', '18', '制造商名称');
INSERT INTO `newscomments_` VALUES ('96', '18', '附加功能');
INSERT INTO `newscomments_` VALUES ('97', '18', '采购地');
INSERT INTO `newscomments_` VALUES ('98', '18', '机身材质');
INSERT INTO `newscomments_` VALUES ('99', '18', '颜色分类');
INSERT INTO `newscomments_` VALUES ('100', '18', '产品名称');
INSERT INTO `newscomments_` VALUES ('101', '18', '操作方式');
INSERT INTO `newscomments_` VALUES ('102', '17', '冰箱冷柜机型');
INSERT INTO `newscomments_` VALUES ('103', '17', '证书状态');
INSERT INTO `newscomments_` VALUES ('104', '17', '箱门结构');
INSERT INTO `newscomments_` VALUES ('105', '17', '美菱冰箱型号');
INSERT INTO `newscomments_` VALUES ('106', '17', '3C产品型号');
INSERT INTO `newscomments_` VALUES ('107', '17', '申请人名称');
INSERT INTO `newscomments_` VALUES ('108', '17', '证书编号');
INSERT INTO `newscomments_` VALUES ('109', '17', '制造商名称');
INSERT INTO `newscomments_` VALUES ('110', '17', '制冷方式');
INSERT INTO `newscomments_` VALUES ('111', '17', '产品名称');
INSERT INTO `newscomments_` VALUES ('112', '17', '能效等级');
INSERT INTO `newscomments_` VALUES ('113', '16', '空调类型');
INSERT INTO `newscomments_` VALUES ('114', '16', '证书状态');
INSERT INTO `newscomments_` VALUES ('115', '16', '证书编号');
INSERT INTO `newscomments_` VALUES ('116', '16', '海信空调型号');
INSERT INTO `newscomments_` VALUES ('117', '16', '工作方式');
INSERT INTO `newscomments_` VALUES ('118', '16', '冷暖类型');
INSERT INTO `newscomments_` VALUES ('119', '16', '产品名称');
INSERT INTO `newscomments_` VALUES ('120', '16', '能效等级');
INSERT INTO `newscomments_` VALUES ('121', '16', '空调功率');
INSERT INTO `newscomments_` VALUES ('122', '16', '适用面积');
INSERT INTO `newscomments_` VALUES ('123', '15', '风格');
INSERT INTO `newscomments_` VALUES ('124', '15', '颜色分类');
INSERT INTO `newscomments_` VALUES ('125', '15', '显示方式');
INSERT INTO `newscomments_` VALUES ('126', '15', '表壳材质');
INSERT INTO `newscomments_` VALUES ('127', '15', '机芯类型');
INSERT INTO `newscomments_` VALUES ('128', '15', '手表镜面材质');
INSERT INTO `newscomments_` VALUES ('129', '15', '机芯产地');
INSERT INTO `newscomments_` VALUES ('130', '15', '表盘厚度');
INSERT INTO `newscomments_` VALUES ('131', '15', '品牌产地');
INSERT INTO `newscomments_` VALUES ('132', '15', '成色');
INSERT INTO `newscomments_` VALUES ('133', '15', '表盘直径');
INSERT INTO `newscomments_` VALUES ('134', '15', '上市时间');
INSERT INTO `newscomments_` VALUES ('135', '15', '表带材质');
INSERT INTO `newscomments_` VALUES ('136', '15', '保修');
INSERT INTO `newscomments_` VALUES ('137', '15', '品牌');
INSERT INTO `newscomments_` VALUES ('138', '15', '形状');
INSERT INTO `newscomments_` VALUES ('139', '15', '防水深度');
INSERT INTO `newscomments_` VALUES ('140', '15', '流行元素');
INSERT INTO `newscomments_` VALUES ('141', '15', '手表种类');
INSERT INTO `newscomments_` VALUES ('142', '15', '型号');
INSERT INTO `newscomments_` VALUES ('143', '14', '风格');
INSERT INTO `newscomments_` VALUES ('144', '14', '颜色分类');
INSERT INTO `newscomments_` VALUES ('145', '14', '显示方式');
INSERT INTO `newscomments_` VALUES ('146', '14', '表壳材质');
INSERT INTO `newscomments_` VALUES ('147', '14', '机芯类型');
INSERT INTO `newscomments_` VALUES ('148', '14', '手表镜面材质');
INSERT INTO `newscomments_` VALUES ('149', '14', '表扣款式');
INSERT INTO `newscomments_` VALUES ('150', '14', '表盘厚度');
INSERT INTO `newscomments_` VALUES ('151', '14', '品牌产地');
INSERT INTO `newscomments_` VALUES ('152', '14', '表盘直径');
INSERT INTO `newscomments_` VALUES ('153', '14', '成色');
INSERT INTO `newscomments_` VALUES ('154', '14', '上市时间');
INSERT INTO `newscomments_` VALUES ('155', '14', '表带材质');
INSERT INTO `newscomments_` VALUES ('156', '14', '保修');
INSERT INTO `newscomments_` VALUES ('157', '14', '品牌');
INSERT INTO `newscomments_` VALUES ('158', '14', '形状');
INSERT INTO `newscomments_` VALUES ('159', '14', '防水深度');
INSERT INTO `newscomments_` VALUES ('160', '14', '表底类型');
INSERT INTO `newscomments_` VALUES ('161', '14', '表冠类型');
INSERT INTO `newscomments_` VALUES ('162', '14', '流行元素');
INSERT INTO `newscomments_` VALUES ('163', '14', '手表种类');
INSERT INTO `newscomments_` VALUES ('164', '14', '型号');
INSERT INTO `newscomments_` VALUES ('165', '13', '风格');
INSERT INTO `newscomments_` VALUES ('166', '13', '大小');
INSERT INTO `newscomments_` VALUES ('167', '13', '内部结构');
INSERT INTO `newscomments_` VALUES ('168', '13', '颜色分类');
INSERT INTO `newscomments_` VALUES ('169', '13', '箱包硬度');
INSERT INTO `newscomments_` VALUES ('170', '13', '款式');
INSERT INTO `newscomments_` VALUES ('171', '13', '图案');
INSERT INTO `newscomments_` VALUES ('172', '13', '成色');
INSERT INTO `newscomments_` VALUES ('173', '13', '里料材质');
INSERT INTO `newscomments_` VALUES ('174', '13', '上市时间');
INSERT INTO `newscomments_` VALUES ('175', '13', '品牌');
INSERT INTO `newscomments_` VALUES ('176', '13', '形状');
INSERT INTO `newscomments_` VALUES ('177', '13', '箱包外袋种类');
INSERT INTO `newscomments_` VALUES ('178', '13', '适用对象');
INSERT INTO `newscomments_` VALUES ('179', '13', '质地');
INSERT INTO `newscomments_` VALUES ('180', '13', '拿包方式');
INSERT INTO `newscomments_` VALUES ('181', '13', '适用场景');
INSERT INTO `newscomments_` VALUES ('182', '13', '提拎部件类型');
INSERT INTO `newscomments_` VALUES ('183', '13', '闭合方式');
INSERT INTO `newscomments_` VALUES ('184', '13', '是否可折叠');
INSERT INTO `newscomments_` VALUES ('185', '13', '有无夹层');
INSERT INTO `newscomments_` VALUES ('186', '13', '货号');
INSERT INTO `newscomments_` VALUES ('187', '13', '皮革材质');
INSERT INTO `newscomments_` VALUES ('188', '12', '销售渠道类型');
INSERT INTO `newscomments_` VALUES ('189', '12', '面料分类');
INSERT INTO `newscomments_` VALUES ('190', '12', '上市年份季节');
INSERT INTO `newscomments_` VALUES ('191', '12', '品牌');
INSERT INTO `newscomments_` VALUES ('192', '12', '货号');
INSERT INTO `newscomments_` VALUES ('193', '12', '基础风格');
INSERT INTO `newscomments_` VALUES ('194', '12', '材质成分');
INSERT INTO `newscomments_` VALUES ('195', '12', '厚薄');
INSERT INTO `newscomments_` VALUES ('196', '11', '风格');
INSERT INTO `newscomments_` VALUES ('197', '11', '鞋面材质');
INSERT INTO `newscomments_` VALUES ('198', '11', '低帮鞋品名');
INSERT INTO `newscomments_` VALUES ('199', '11', '鞋底材质');
INSERT INTO `newscomments_` VALUES ('200', '11', '颜色分类');
INSERT INTO `newscomments_` VALUES ('201', '11', '上市年份季节');
INSERT INTO `newscomments_` VALUES ('202', '11', '款式');
INSERT INTO `newscomments_` VALUES ('203', '11', '图案');
INSERT INTO `newscomments_` VALUES ('204', '10', '鞋面内里材质');
INSERT INTO `newscomments_` VALUES ('205', '10', '季节');
INSERT INTO `newscomments_` VALUES ('206', '10', '细分风格');
INSERT INTO `newscomments_` VALUES ('207', '10', '鞋跟高');
INSERT INTO `newscomments_` VALUES ('208', '10', '品牌');
INSERT INTO `newscomments_` VALUES ('209', '10', '适用对象');
INSERT INTO `newscomments_` VALUES ('210', '10', '销售渠道类型');
INSERT INTO `newscomments_` VALUES ('211', '10', '功能');
INSERT INTO `newscomments_` VALUES ('212', '10', '鞋制作工艺');
INSERT INTO `newscomments_` VALUES ('213', '10', '尺码');
INSERT INTO `newscomments_` VALUES ('214', '10', '闭合方式');
INSERT INTO `newscomments_` VALUES ('215', '10', '流行元素');
INSERT INTO `newscomments_` VALUES ('216', '10', '跟底款式');
INSERT INTO `newscomments_` VALUES ('217', '10', '货号');
INSERT INTO `newscomments_` VALUES ('218', '10', '鞋头款式');
INSERT INTO `newscomments_` VALUES ('219', '10', '鞋垫材质');
INSERT INTO `newscomments_` VALUES ('220', '10', '场合');
INSERT INTO `newscomments_` VALUES ('221', '9', '适用年龄');
INSERT INTO `newscomments_` VALUES ('222', '9', '颜色分类');
INSERT INTO `newscomments_` VALUES ('223', '9', '上市年份季节');
INSERT INTO `newscomments_` VALUES ('224', '9', '尺码');
INSERT INTO `newscomments_` VALUES ('225', '9', '货号');
INSERT INTO `newscomments_` VALUES ('226', '9', '品牌');
INSERT INTO `newscomments_` VALUES ('227', '9', '材质成分');
INSERT INTO `newscomments_` VALUES ('228', '8', '品牌');
INSERT INTO `newscomments_` VALUES ('229', '8', '产地');
INSERT INTO `newscomments_` VALUES ('230', '8', '上市时间');
INSERT INTO `newscomments_` VALUES ('231', '8', '型号');
INSERT INTO `newscomments_` VALUES ('232', '7', '功能');
INSERT INTO `newscomments_` VALUES ('233', '7', '适用性别');
INSERT INTO `newscomments_` VALUES ('234', '7', '风格');
INSERT INTO `newscomments_` VALUES ('235', '6', '价格区间');
INSERT INTO `newscomments_` VALUES ('236', '6', '眼镜配件类型');
INSERT INTO `newscomments_` VALUES ('237', '6', '是否商场同款');
INSERT INTO `newscomments_` VALUES ('238', '5', '镜片材质');
INSERT INTO `newscomments_` VALUES ('239', '5', '货号');
INSERT INTO `newscomments_` VALUES ('240', '5', '颜色分类');
INSERT INTO `newscomments_` VALUES ('241', '5', '是否可调');
INSERT INTO `newscomments_` VALUES ('242', '5', '适合脸型');
INSERT INTO `newscomments_` VALUES ('243', '4', '产地');
INSERT INTO `newscomments_` VALUES ('244', '4', '证书状态');
INSERT INTO `newscomments_` VALUES ('245', '4', '3C产品型号');
INSERT INTO `newscomments_` VALUES ('246', '4', '申请人名称');
INSERT INTO `newscomments_` VALUES ('247', '4', '安装接口');
INSERT INTO `newscomments_` VALUES ('248', '4', '适合体重');
INSERT INTO `newscomments_` VALUES ('249', '3', '证书编号');
INSERT INTO `newscomments_` VALUES ('250', '3', '型号');
INSERT INTO `newscomments_` VALUES ('251', '3', '制造商名称');
INSERT INTO `newscomments_` VALUES ('252', '3', '颜色分类');
INSERT INTO `newscomments_` VALUES ('253', '2', '款式');
INSERT INTO `newscomments_` VALUES ('254', '2', '产品名称');
INSERT INTO `newscomments_` VALUES ('255', '2', '人体固定方式');
INSERT INTO `newscomments_` VALUES ('256', '1', '适用');
INSERT INTO `newscomments_` VALUES ('257', '1', '适用年龄');
INSERT INTO `newscomments_` VALUES ('272', '1', 'producy');
INSERT INTO `newscomments_` VALUES ('273', '1', 'mo');
INSERT INTO `newscomments_` VALUES ('274', '1', '32');
INSERT INTO `newscomments_` VALUES ('277', '1', '54天3');
INSERT INTO `newscomments_` VALUES ('278', '1', '54天3');
INSERT INTO `newscomments_` VALUES ('279', '1', '54天3');
INSERT INTO `newscomments_` VALUES ('280', '1', '54天3');

-- ----------------------------
-- Table structure for property_
-- ----------------------------
DROP TABLE IF EXISTS `property_`;
CREATE TABLE `property_` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cid` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=275 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of property_
-- ----------------------------
INSERT INTO `property_` VALUES ('1', '24', '品牌');
INSERT INTO `property_` VALUES ('2', '24', '证书状态');
INSERT INTO `property_` VALUES ('3', '24', '3C产品型号');
INSERT INTO `property_` VALUES ('4', '24', '申请人名称');
INSERT INTO `property_` VALUES ('5', '24', '证书编号');
INSERT INTO `property_` VALUES ('6', '24', '分辨率');
INSERT INTO `property_` VALUES ('7', '24', '型号');
INSERT INTO `property_` VALUES ('8', '24', '制造商名称');
INSERT INTO `property_` VALUES ('9', '24', '网络连接方式');
INSERT INTO `property_` VALUES ('10', '24', '产品名称');
INSERT INTO `property_` VALUES ('11', '24', '能效等级');
INSERT INTO `property_` VALUES ('12', '24', '3D类型');
INSERT INTO `property_` VALUES ('13', '24', '操作系统');
INSERT INTO `property_` VALUES ('14', '23', '品牌');
INSERT INTO `property_` VALUES ('15', '23', '冲水按键类型');
INSERT INTO `property_` VALUES ('16', '23', '坐便器类型');
INSERT INTO `property_` VALUES ('17', '23', '盖板是否缓冲');
INSERT INTO `property_` VALUES ('18', '23', '型号');
INSERT INTO `property_` VALUES ('19', '23', '坐便器冲水方式');
INSERT INTO `property_` VALUES ('20', '23', '排水方式');
INSERT INTO `property_` VALUES ('21', '23', '材质');
INSERT INTO `property_` VALUES ('22', '23', '最小坑距');
INSERT INTO `property_` VALUES ('23', '23', '承重');
INSERT INTO `property_` VALUES ('24', '23', '颜色分类');
INSERT INTO `property_` VALUES ('25', '23', '坐便冲水量');
INSERT INTO `property_` VALUES ('26', '23', '同城服务');
INSERT INTO `property_` VALUES ('27', '22', '风格');
INSERT INTO `property_` VALUES ('28', '22', '城市');
INSERT INTO `property_` VALUES ('29', '22', '面料饰面工艺');
INSERT INTO `property_` VALUES ('30', '22', '是否带储物空间');
INSERT INTO `property_` VALUES ('31', '22', '包装体积');
INSERT INTO `property_` VALUES ('32', '22', '颜色分类');
INSERT INTO `property_` VALUES ('33', '22', '附加功能');
INSERT INTO `property_` VALUES ('34', '22', '是否可拆洗');
INSERT INTO `property_` VALUES ('35', '22', '结构工艺');
INSERT INTO `property_` VALUES ('36', '22', '设计元素');
INSERT INTO `property_` VALUES ('37', '22', '几人坐');
INSERT INTO `property_` VALUES ('38', '22', '图案');
INSERT INTO `property_` VALUES ('39', '22', '是否组装');
INSERT INTO `property_` VALUES ('40', '22', '面料');
INSERT INTO `property_` VALUES ('41', '22', '可送货/安装');
INSERT INTO `property_` VALUES ('42', '22', '木质结构工艺');
INSERT INTO `property_` VALUES ('43', '22', '沙发组合形式');
INSERT INTO `property_` VALUES ('44', '22', '产地');
INSERT INTO `property_` VALUES ('45', '22', '是否可定制');
INSERT INTO `property_` VALUES ('46', '22', '品牌');
INSERT INTO `property_` VALUES ('47', '22', '适用对象');
INSERT INTO `property_` VALUES ('48', '22', '材质');
INSERT INTO `property_` VALUES ('49', '22', '款式定位');
INSERT INTO `property_` VALUES ('50', '22', '填充物');
INSERT INTO `property_` VALUES ('51', '22', '填充物硬度');
INSERT INTO `property_` VALUES ('52', '22', '出租车是否可运输');
INSERT INTO `property_` VALUES ('53', '22', '型号');
INSERT INTO `property_` VALUES ('54', '22', '木质材质');
INSERT INTO `property_` VALUES ('55', '22', '是否可预售');
INSERT INTO `property_` VALUES ('56', '22', '安装说明详情');
INSERT INTO `property_` VALUES ('57', '21', '品牌');
INSERT INTO `property_` VALUES ('58', '21', '证书状态');
INSERT INTO `property_` VALUES ('59', '21', '3C产品型号');
INSERT INTO `property_` VALUES ('60', '21', '申请人名称');
INSERT INTO `property_` VALUES ('61', '21', '证书编号');
INSERT INTO `property_` VALUES ('62', '21', '型号');
INSERT INTO `property_` VALUES ('63', '21', '控制方式');
INSERT INTO `property_` VALUES ('64', '21', '制造商名称');
INSERT INTO `property_` VALUES ('65', '21', '款式');
INSERT INTO `property_` VALUES ('66', '21', '产品名称');
INSERT INTO `property_` VALUES ('67', '21', '能效等级');
INSERT INTO `property_` VALUES ('68', '20', '上市时间');
INSERT INTO `property_` VALUES ('69', '20', '款式');
INSERT INTO `property_` VALUES ('70', '20', '是否商场同款');
INSERT INTO `property_` VALUES ('71', '20', '货号');
INSERT INTO `property_` VALUES ('72', '20', '品牌');
INSERT INTO `property_` VALUES ('73', '19', '液晶显示');
INSERT INTO `property_` VALUES ('74', '19', '尘盒容量');
INSERT INTO `property_` VALUES ('75', '19', '外观造型');
INSERT INTO `property_` VALUES ('76', '19', '功能');
INSERT INTO `property_` VALUES ('77', '19', '最高高度');
INSERT INTO `property_` VALUES ('78', '19', '碰撞保护');
INSERT INTO `property_` VALUES ('79', '19', '是否自动充电');
INSERT INTO `property_` VALUES ('80', '19', '电池容量');
INSERT INTO `property_` VALUES ('81', '19', '有无虚拟墙');
INSERT INTO `property_` VALUES ('82', '19', '是否有定时预约功能');
INSERT INTO `property_` VALUES ('83', '19', '货号');
INSERT INTO `property_` VALUES ('84', '19', '颜色分类');
INSERT INTO `property_` VALUES ('85', '19', '清扫路线');
INSERT INTO `property_` VALUES ('86', '19', '是否带遥控器');
INSERT INTO `property_` VALUES ('87', '18', '品牌');
INSERT INTO `property_` VALUES ('88', '18', '转速');
INSERT INTO `property_` VALUES ('89', '18', '证书状态');
INSERT INTO `property_` VALUES ('90', '18', '3C产品型号');
INSERT INTO `property_` VALUES ('91', '18', '申请人名称');
INSERT INTO `property_` VALUES ('92', '18', '额定功率');
INSERT INTO `property_` VALUES ('93', '18', '证书编号');
INSERT INTO `property_` VALUES ('94', '18', '型号');
INSERT INTO `property_` VALUES ('95', '18', '制造商名称');
INSERT INTO `property_` VALUES ('96', '18', '附加功能');
INSERT INTO `property_` VALUES ('97', '18', '采购地');
INSERT INTO `property_` VALUES ('98', '18', '机身材质');
INSERT INTO `property_` VALUES ('99', '18', '颜色分类');
INSERT INTO `property_` VALUES ('100', '18', '产品名称');
INSERT INTO `property_` VALUES ('101', '18', '操作方式');
INSERT INTO `property_` VALUES ('102', '17', '冰箱冷柜机型');
INSERT INTO `property_` VALUES ('103', '17', '证书状态');
INSERT INTO `property_` VALUES ('104', '17', '箱门结构');
INSERT INTO `property_` VALUES ('105', '17', '美菱冰箱型号');
INSERT INTO `property_` VALUES ('106', '17', '3C产品型号');
INSERT INTO `property_` VALUES ('107', '17', '申请人名称');
INSERT INTO `property_` VALUES ('108', '17', '证书编号');
INSERT INTO `property_` VALUES ('109', '17', '制造商名称');
INSERT INTO `property_` VALUES ('110', '17', '制冷方式');
INSERT INTO `property_` VALUES ('111', '17', '产品名称');
INSERT INTO `property_` VALUES ('112', '17', '能效等级');
INSERT INTO `property_` VALUES ('113', '16', '空调类型');
INSERT INTO `property_` VALUES ('114', '16', '证书状态');
INSERT INTO `property_` VALUES ('115', '16', '证书编号');
INSERT INTO `property_` VALUES ('116', '16', '海信空调型号');
INSERT INTO `property_` VALUES ('117', '16', '工作方式');
INSERT INTO `property_` VALUES ('118', '16', '冷暖类型');
INSERT INTO `property_` VALUES ('119', '16', '产品名称');
INSERT INTO `property_` VALUES ('120', '16', '能效等级');
INSERT INTO `property_` VALUES ('121', '16', '空调功率');
INSERT INTO `property_` VALUES ('122', '16', '适用面积');
INSERT INTO `property_` VALUES ('123', '15', '风格');
INSERT INTO `property_` VALUES ('124', '15', '颜色分类');
INSERT INTO `property_` VALUES ('125', '15', '显示方式');
INSERT INTO `property_` VALUES ('126', '15', '表壳材质');
INSERT INTO `property_` VALUES ('127', '15', '机芯类型');
INSERT INTO `property_` VALUES ('128', '15', '手表镜面材质');
INSERT INTO `property_` VALUES ('129', '15', '机芯产地');
INSERT INTO `property_` VALUES ('130', '15', '表盘厚度');
INSERT INTO `property_` VALUES ('131', '15', '品牌产地');
INSERT INTO `property_` VALUES ('132', '15', '成色');
INSERT INTO `property_` VALUES ('133', '15', '表盘直径');
INSERT INTO `property_` VALUES ('134', '15', '上市时间');
INSERT INTO `property_` VALUES ('135', '15', '表带材质');
INSERT INTO `property_` VALUES ('136', '15', '保修');
INSERT INTO `property_` VALUES ('137', '15', '品牌');
INSERT INTO `property_` VALUES ('138', '15', '形状');
INSERT INTO `property_` VALUES ('139', '15', '防水深度');
INSERT INTO `property_` VALUES ('140', '15', '流行元素');
INSERT INTO `property_` VALUES ('141', '15', '手表种类');
INSERT INTO `property_` VALUES ('142', '15', '型号');
INSERT INTO `property_` VALUES ('143', '14', '风格');
INSERT INTO `property_` VALUES ('144', '14', '颜色分类');
INSERT INTO `property_` VALUES ('145', '14', '显示方式');
INSERT INTO `property_` VALUES ('146', '14', '表壳材质');
INSERT INTO `property_` VALUES ('147', '14', '机芯类型');
INSERT INTO `property_` VALUES ('148', '14', '手表镜面材质');
INSERT INTO `property_` VALUES ('149', '14', '表扣款式');
INSERT INTO `property_` VALUES ('150', '14', '表盘厚度');
INSERT INTO `property_` VALUES ('151', '14', '品牌产地');
INSERT INTO `property_` VALUES ('152', '14', '表盘直径');
INSERT INTO `property_` VALUES ('153', '14', '成色');
INSERT INTO `property_` VALUES ('154', '14', '上市时间');
INSERT INTO `property_` VALUES ('155', '14', '表带材质');
INSERT INTO `property_` VALUES ('156', '14', '保修');
INSERT INTO `property_` VALUES ('157', '14', '品牌');
INSERT INTO `property_` VALUES ('158', '14', '形状');
INSERT INTO `property_` VALUES ('159', '14', '防水深度');
INSERT INTO `property_` VALUES ('160', '14', '表底类型');
INSERT INTO `property_` VALUES ('161', '14', '表冠类型');
INSERT INTO `property_` VALUES ('162', '14', '流行元素');
INSERT INTO `property_` VALUES ('163', '14', '手表种类');
INSERT INTO `property_` VALUES ('164', '14', '型号');
INSERT INTO `property_` VALUES ('165', '13', '风格');
INSERT INTO `property_` VALUES ('166', '13', '大小');
INSERT INTO `property_` VALUES ('167', '13', '内部结构');
INSERT INTO `property_` VALUES ('168', '13', '颜色分类');
INSERT INTO `property_` VALUES ('169', '13', '箱包硬度');
INSERT INTO `property_` VALUES ('170', '13', '款式');
INSERT INTO `property_` VALUES ('171', '13', '图案');
INSERT INTO `property_` VALUES ('172', '13', '成色');
INSERT INTO `property_` VALUES ('173', '13', '里料材质');
INSERT INTO `property_` VALUES ('174', '13', '上市时间');
INSERT INTO `property_` VALUES ('175', '13', '品牌');
INSERT INTO `property_` VALUES ('176', '13', '形状');
INSERT INTO `property_` VALUES ('177', '13', '箱包外袋种类');
INSERT INTO `property_` VALUES ('178', '13', '适用对象');
INSERT INTO `property_` VALUES ('179', '13', '质地');
INSERT INTO `property_` VALUES ('180', '13', '拿包方式');
INSERT INTO `property_` VALUES ('181', '13', '适用场景');
INSERT INTO `property_` VALUES ('182', '13', '提拎部件类型');
INSERT INTO `property_` VALUES ('183', '13', '闭合方式');
INSERT INTO `property_` VALUES ('184', '13', '是否可折叠');
INSERT INTO `property_` VALUES ('185', '13', '有无夹层');
INSERT INTO `property_` VALUES ('186', '13', '货号');
INSERT INTO `property_` VALUES ('187', '13', '皮革材质');
INSERT INTO `property_` VALUES ('188', '12', '销售渠道类型');
INSERT INTO `property_` VALUES ('189', '12', '面料分类');
INSERT INTO `property_` VALUES ('190', '12', '上市年份季节');
INSERT INTO `property_` VALUES ('191', '12', '品牌');
INSERT INTO `property_` VALUES ('192', '12', '货号');
INSERT INTO `property_` VALUES ('193', '12', '基础风格');
INSERT INTO `property_` VALUES ('194', '12', '材质成分');
INSERT INTO `property_` VALUES ('195', '12', '厚薄');
INSERT INTO `property_` VALUES ('196', '11', '风格');
INSERT INTO `property_` VALUES ('197', '11', '鞋面材质');
INSERT INTO `property_` VALUES ('198', '11', '低帮鞋品名');
INSERT INTO `property_` VALUES ('199', '11', '鞋底材质');
INSERT INTO `property_` VALUES ('200', '11', '颜色分类');
INSERT INTO `property_` VALUES ('201', '11', '上市年份季节');
INSERT INTO `property_` VALUES ('202', '11', '款式');
INSERT INTO `property_` VALUES ('203', '11', '图案');
INSERT INTO `property_` VALUES ('204', '10', '鞋面内里材质');
INSERT INTO `property_` VALUES ('205', '10', '季节');
INSERT INTO `property_` VALUES ('206', '10', '细分风格');
INSERT INTO `property_` VALUES ('207', '10', '鞋跟高');
INSERT INTO `property_` VALUES ('208', '10', '品牌');
INSERT INTO `property_` VALUES ('209', '10', '适用对象');
INSERT INTO `property_` VALUES ('210', '10', '销售渠道类型');
INSERT INTO `property_` VALUES ('211', '10', '功能');
INSERT INTO `property_` VALUES ('212', '10', '鞋制作工艺');
INSERT INTO `property_` VALUES ('213', '10', '尺码');
INSERT INTO `property_` VALUES ('214', '10', '闭合方式');
INSERT INTO `property_` VALUES ('215', '10', '流行元素');
INSERT INTO `property_` VALUES ('216', '10', '跟底款式');
INSERT INTO `property_` VALUES ('217', '10', '货号');
INSERT INTO `property_` VALUES ('218', '10', '鞋头款式');
INSERT INTO `property_` VALUES ('219', '10', '鞋垫材质');
INSERT INTO `property_` VALUES ('220', '10', '场合');
INSERT INTO `property_` VALUES ('221', '9', '适用年龄');
INSERT INTO `property_` VALUES ('222', '9', '颜色分类');
INSERT INTO `property_` VALUES ('223', '9', '上市年份季节');
INSERT INTO `property_` VALUES ('224', '9', '尺码');
INSERT INTO `property_` VALUES ('225', '9', '货号');
INSERT INTO `property_` VALUES ('226', '9', '品牌');
INSERT INTO `property_` VALUES ('227', '9', '材质成分');
INSERT INTO `property_` VALUES ('228', '8', '品牌');
INSERT INTO `property_` VALUES ('229', '8', '产地');
INSERT INTO `property_` VALUES ('230', '8', '上市时间');
INSERT INTO `property_` VALUES ('231', '8', '型号');
INSERT INTO `property_` VALUES ('232', '7', '功能');
INSERT INTO `property_` VALUES ('233', '7', '适用性别');
INSERT INTO `property_` VALUES ('234', '7', '风格');
INSERT INTO `property_` VALUES ('235', '6', '价格区间');
INSERT INTO `property_` VALUES ('236', '6', '眼镜配件类型');
INSERT INTO `property_` VALUES ('237', '6', '是否商场同款');
INSERT INTO `property_` VALUES ('238', '5', '镜片材质');
INSERT INTO `property_` VALUES ('239', '5', '货号');
INSERT INTO `property_` VALUES ('240', '5', '颜色分类');
INSERT INTO `property_` VALUES ('241', '5', '是否可调');
INSERT INTO `property_` VALUES ('242', '5', '适合脸型');
INSERT INTO `property_` VALUES ('243', '4', '产地');
INSERT INTO `property_` VALUES ('244', '4', '证书状态');
INSERT INTO `property_` VALUES ('245', '4', '3C产品型号');
INSERT INTO `property_` VALUES ('246', '4', '申请人名称');
INSERT INTO `property_` VALUES ('247', '4', '安装接口');
INSERT INTO `property_` VALUES ('248', '4', '适合体重');
INSERT INTO `property_` VALUES ('249', '3', '证书编号');
INSERT INTO `property_` VALUES ('250', '3', '型号');
INSERT INTO `property_` VALUES ('251', '3', '制造商名称');
INSERT INTO `property_` VALUES ('252', '3', '颜色分类');
INSERT INTO `property_` VALUES ('253', '2', '款式');
INSERT INTO `property_` VALUES ('254', '2', '产品名称');
INSERT INTO `property_` VALUES ('255', '2', '人体固定方式');
INSERT INTO `property_` VALUES ('256', '1', '适用');
INSERT INTO `property_` VALUES ('257', '1', '适用年龄');
INSERT INTO `property_` VALUES ('272', '1', 'producy');
INSERT INTO `property_` VALUES ('273', '1', 'mo');
INSERT INTO `property_` VALUES ('274', '1', '32');
